import React from "react";

const DynamicRouter = () => {
  const useInfo = JSON.parse(localStorage.getItem("useInfo") || "{}");
  if (Object.keys(useInfo).length !== 0) {
    const menus = useInfo;
  }
  return <div>DynamicRouter</div>;
};
const aa = {
  status: "success",
  message:
    '[{"id":"1","parentId":null,"key":"1","label":"新豪轴承","icon":"SettingOutlined","children":[{"id":"2","parentId":"1","key":"/add_part_flow_card","label":"零件流转卡添加","icon":null,"children":null},{"id":"3","parentId":"1","key":"/add_assembly_flow_card","label":"装配流转卡添加","icon":null,"children":null},{"id":"4","parentId":"1","key":"/flow_card_query","label":"流转卡查询","icon":null,"children":null},{"id":"5","parentId":"1","key":"/operator_simple_task","label":"操作工简易作业","icon":null,"children":null},{"id":"6","parentId":"1","key":"/flow_card_cancel","label":"流转卡作废","icon":null,"children":null},{"id":"7","parentId":"1","key":"/add_employee_info","label":"员工信息添加","icon":null,"children":null},{"id":"8","parentId":"1","key":"/full_inspection_defect_rate","label":"全检不良率","icon":null,"children":null}]},{"id":"9","parentId":null,"key":"2","label":"链条流转卡","icon":"ProfileOutlined","children":[{"id":"10","parentId":"9","key":"/issue_chainboards_semi_finished_part_flow_card","label":"下发链板半品零件流转卡","icon":null,"children":null},{"id":"11","parentId":"9","key":"/issue_rollernest_semi_finished_part_flow_card","label":"下发套滚销半品零件流转卡","icon":null,"children":null},{"id":"12","parentId":"9","key":"/issue_finished_part_flow_card","label":"下发成品零件流转卡","icon":null,"children":null},{"id":"13","parentId":"9","key":"/issue_outsourcing_flow_card","label":"下发外协外购流转卡","icon":null,"children":null},{"id":"14","parentId":"9","key":"/issue_replenishment_order_flow_card","label":"下发补单流转卡","icon":null,"children":null},{"id":"15","parentId":"9","key":"/part_flow_card_query","label":"零件流转卡查询","icon":null,"children":null},{"id":"16","parentId":"9","key":"/part_flow_card_print","label":"零件流转卡打印","icon":null,"children":null},{"id":"17","parentId":"9","key":"/order_completion_status","label":"订单完成情况统计","icon":null,"children":null},{"id":"18","parentId":"9","key":"/flow_card_storage_info","label":"流转卡入库信息查询","icon":null,"children":null},{"id":"19","parentId":"9","key":"/material_rework_process_card","label":"物料重工流程卡添加","icon":null,"children":null},{"id":"20","parentId":"9","key":"/heavy_industry_process_card","label":"重工流程卡查询","icon":null,"children":null},{"id":"21","parentId":"9","key":"/logistics_heat_treatment_ingredients","label":"物流-热处理配料查询","icon":null,"children":null},{"id":"22","parentId":"9","key":"/quality_inspection_outsourcing_inspection","label":"品检-外购外协报检查询","icon":null,"children":null},{"id":"23","parentId":"9","key":"/heat_treatment_furnace_operation","label":"热处理炉台作业","icon":null,"children":null},{"id":"24","parentId":"9","key":"/update_deburring_rounding_furnace","label":"甩毛刺-甩圆角-炉台变更","icon":null,"children":null},{"id":"25","parentId":"9","key":"/query_raw_material_inventory_inquiry","label":"生料库存查询","icon":null,"children":null},{"id":"26","parentId":"9","key":"/query_process_incomplete","label":"工艺未完成查询","icon":null,"children":null},{"id":"27","parentId":"9","key":"/add_employee_info","label":"员工信息添加","icon":null,"children":null}]}]',
};

export default DynamicRouter;
